version: '3.8'

services:
  omnistream:
    image: ghcr.io/winky2000/omnistream:latest
    container_name: omnistream
    ports:
      - "3000:3000"
    volumes:
      - ./servers.json:/usr/src/app/servers.json
    restart: unless-stopped
    environment:
      - NODE_ENV=production
